### ISSUE TITLE
paragraphs sometimes break around adverts in body

### ISSUE THREAD

**Issue by MrBryan** [TheTyee/design-article.thetyee.ca#171]
![image](https://cloud.githubusercontent.com/assets/1721891/16174344/68c88ece-3572-11e6-9e2b-b95ef61bbbc6.png)

This is on firefox

**Comment by MrBryan** [comment]
seems to have to do with close proximity of aside on the right (related story) and advert aside.   I personally don't think this is a show-stopper as it only seems to happen rarely but if we can whack it that would be good

**Comment by MrBryan** [comment]
actually this is a bit pervasive on Firefox.. bumping it up

**Comment by alexgreen** [comment]
Yeah the layout interaction when these 2 kinds of asides come into close proximity is something that I expected might cause problems. 

Can you post links to some pages where this occurs? (and does Litmus provide links that go directly to a specific page + browser version test?)

Does this also occur when figures and asides come into proximity, or is it only a problem among asides? If the latter is the case (i.e. figures don't exhibit the problem) then the markup and css of the figures might   suggest a solution for aside.ad-box--bigbox

**Comment by phillipadsmith** [comment]
More examples:
http://preview.thetyee.ca/Opinion/2011/12/27/BCRail/index.html

<img width="376" alt="how_bc_rail_was_made_to_disappear___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16433701/761c58f0-3d40-11e6-944f-808fe92dc798.png">

What's going on with this issue, Gents? This is kinda' high priority.

**Comment by MrBryan** [comment]
I backed out any of my medium image treatment css that affects ads.  This issue can be reproduced in philips ad-test-1.html on the repo. 

I currently do not have a solution. As you can see, the position of the ad has no obvious relationship to the location it is actually placed between `<p>` elements.

**Comment by MrBryan** [comment]
I'm assigning this to Alex. The advert aside should appear right where the CMS spits it out, riight? between the two paragraphs where it is actually outputted... this does not happen now, somehow the ads get floated down to first images on the right etc that shouldn't be in play.

**Comment by alexgreen** [comment]
(Still not back in Canada yet, but just have a few min to look over the threads.)

Thanks for documented the problem. Any other examples you can provide screenshots and links to would be great. I'll take a close look when I'm back.

@phillipadsmith what browser and platform are you seeing that issue on? Does it only happen in narrow views? 
When I look at http://preview.thetyee.ca/Opinion/2011/12/27/BCRail/index.html on chrome OSX I don't see that problem (screenshot attached). However the actual ad content has disappeared again (but in this case it does seem to be an ad server issue because the iframe is present but has nothing in its body)

@MrBryan and @phillipadsmith are you ever seeing this problem occur with figures, or is it only with the asides that contain ads?

> The advert aside should appear right where the CMS spits it out, riight? between the two paragraphs where it is actually outputted

No, it often won't appear exactly at that point, because (due to its float property and interaction with other floats) it will adjust position depending on other elements that are in proximity. This is actually necessary because it (ideally) prevents main-col elements from colliding with adjacent asides in narrow views. (Although there's obvs some bugs to iron out.) I've been assuming that ads don't have to appear in such an _exact_ location and that it won't matter if they're a paragraph earlier or later.

![screen shot 2016-07-06 at 1 46 35 am](https://cloud.githubusercontent.com/assets/151099/16592464/c2a14de4-431b-11e6-94de-5e7ead3a78db.png)
.

**Comment by MrBryan** [comment]
Hmm well, if it were a paragraph or two that would be better (but still not really because the editors specifically choose where it will appear in the element flow for a graceful stop)  but quite often it is half way down the story (further than intended) and then both ads show up at once because they were both trying to clear the same elements

**Comment by MrBryan** [comment]
notice on the story you took a screenshot from how the two ads (the missing image from the one is not part of the issue that's geo targettign we're pretty sure) they two ads are only two spots away from one another, but in the mark up they are 16 slots (paragraph elements / asides / whatever) apart:

![image](https://cloud.githubusercontent.com/assets/1721891/16597136/5d79094e-42c5-11e6-9609-541bc72d7e19.png)

![image](https://cloud.githubusercontent.com/assets/1721891/16597182/9228e7ae-42c5-11e6-818f-5ef457588aff.png)

**Comment by MrBryan** [comment]
I realize there are practical limitations of real estate on the side especially until the related stories are cut down to 1 for the legacy stories but we give them the ability to control both the ad locations and the individual related stories and related images and they probably relate to a specific part of the story per the location chosen so we should try to find a way to be precise if we can

**Comment by MrBryan** [comment]
Another example -- ads should be four paragraphs apart but show one after the other:

http://preview.thetyee.ca/News/2015/02/23/Four-Sisters-Coop-Profile/

![image](https://cloud.githubusercontent.com/assets/1721891/16622860/a0c3499a-4369-11e6-8859-b41a1f11ad02.png)

![image](https://cloud.githubusercontent.com/assets/1721891/16622873/a90eda24-4369-11e6-8a41-85f3e5623e62.png)

**Comment by phillipadsmith** [comment]
Related:

Name of issue: Back-to-back ads in a story
URL: http://preview.thetyee.ca/News/2016/07/02/Kingsgate-Mall-VSB/
Description: In this story, two ads appear in succession (i.e. one ad on top of another), which looks a bit strange. Not sure if it’s supposed to look like that.
Reporter: Robyn S. 

<img width="322" alt="tyee_staff_consolidated_article_page_feedback_-_google_docs" src="https://cloud.githubusercontent.com/assets/34128/16673919/704be0c0-4467-11e6-975e-9daafb8f886a.png">

**Comment by alexgreen** [comment]
I have an all-day board meeting today but I'll have a closer look at this in the evening.

I think it may be fairly easy to fix in wider views.

But part of the problem seems to be that editorial is specifying the ads too close together. For example, on http://preview.thetyee.ca/News/2015/02/23/Four-Sisters-Coop-Profile/ the ads are actually appearing exactly where they're written in the markup (on OSX chrome at all view widths).

In the case of http://preview.thetyee.ca/News/2016/07/02/Kingsgate-Mall-VSB/ the ads are again appearing exactly where they occur in the markup. (see screenshot attached) So the problem seems to be that editorial spec'ed them to appear directly next to each other. 

In the case of http://preview.thetyee.ca/Opinion/2011/12/27/BCRail/index.html the first ad is getting pushed down in some views because the featured image and half-page ad have been moved out of the feature-media section and into the article__body. Obviously that is going to push down everything because there simply is no room. (That's why those things were in the featured-media section.) When you have a featured image, a half-page, a related story, a bigbox ad and an ask block all right at the top of an article things simply have to move around. I think the fact that these things all _do_ fit without breaking the layout is actually a testament to resilience (dare I say "resiliency"?) of the design. Given these content conditions, we're probably looking at the best possible outcome.
But there's a couple things that could be done to dramatically improve the layout:
Move the featured image and half-page ad up into the featured-media section; and/or move the messaging block and related story block further down. In any case the messaging block should definitely be moved further down by default because we have a common problem of blocks getting clumped together at the top of every story.

![screen shot 2016-07-10 at 1 31 21 am](https://cloud.githubusercontent.com/assets/151099/16712565/d6ce7540-463f-11e6-9072-4220e9a9892f.png)

**Comment by alexgreen** [comment]
> What's going on with this issue, Gents? This is kinda' high priority.

@phillipadsmith I think we can safely say the "WTF?" has been solved, yes? Now that the floats have been restored I don't see any of this weird behaviour of the ad block elements breaking apart or bleeding into adjacent figures. I'm no longer able to replicate that behaviour.

**Comment by alexgreen** [comment]
In views wider than 976px the ad-box--bigbox and normal-size figures are not in danger of colliding with asides. So in the interest of keeping them closer to their markup position I've set a breakpoint there to remove their floats. f581fa0b3e52f2f6347338b2ffc969f1650f1fa3 (xl and xxl figures extend beyond the edges of the main-col container so they need to keep floating.)

@phillipadsmith and @MrBryan I've tested this and it seems to work in all cases, but please let me know if you notice any gaps or collisions.

**Comment by alexgreen** [comment]
I have an idea for how I can completely eliminate the need to float the ads. I'll try that later today. If it works that will get us very close to our goal of displaying all objects at the exact position they appear in the markup.

**Comment by alexgreen** [comment]
It would be ideal if we could maintain all figures and ads at their marked up position and get the less important elements (like messaging blocks, related stories, fact-boxes, presents blocks, etc) to just float around (or after) them but this doesn't seem possible possible —it results in gaps in the column when the viewport gets narrower.

**Comment by phillipadsmith** [comment]
> @phillipadsmith and @MrBryan I've tested this and it seems to work in all cases, but please let me know if you notice any gaps or collisions.

@MrBryan How's it looking to you? 

I'm still seeing ads on top of each other as of this morning, but I'm not sure if any changes have been implemented...?

> @phillipadsmith I think we can safely say the "WTF?" has been solved, yes?

Yes, I'm glad it's clear to everyone why this is/what happening! :-)

> Now that the floats have been restored I don't see any of this weird behaviour of the ad block elements breaking apart or bleeding into adjacent figures. I'm no longer able to replicate that behaviour.

Okay, waiting for @MrBryan to weigh-in here...

**Comment by MrBryan** [comment]
I'm not sure what changed since I posted those screens but indeed they are showing at the correct spot now

**Comment by phillipadsmith** [comment]
> I'm not sure what changed since I posted those screens but indeed they are showing at the correct spot now

Closing this for now then.

**Comment by alexgreen** [comment]
To recap, the ads on http://preview.thetyee.ca/News/2016/07/02/Kingsgate-Mall-VSB/ are indeed still on top of each other. But this is because the html specifies that they _should be_ directly next to each other (dev screenshot below). So the problem appears to be caused by the content entry and not by the presentation.

Is this common? If so, then it's probably better to just inject the ad blocks at regular intervals via automation rather than make editorial insert them.

![screen shot 2016-07-11 at 3 47 57 pm](https://cloud.githubusercontent.com/assets/151099/16749517/abfa1b62-477f-11e6-8ee1-9c434d6fa279.png)

**Comment by alexgreen** [comment]
I said,

> I have an idea for how I can completely eliminate the need to float the ads. I'll try that later today. If it works that will get us very close to our goal of displaying all objects at the exact position they appear in the markup.

But if this is no longer a priority then I'll post it as a separate issue and hold off on it until later. #270

**Comment by MrBryan** [comment]
No they won't end up next to one another. By default they are  "position" 5 and 17, so for this to happen someone would have to override and set ad one to position "16" for instance.

**Comment by MrBryan** [comment]
which is what happened here - the story is optimized for the old layout but new layouts they will choose the spot and be able to see any issues

**Comment by phillipadsmith** [comment]
We should give @robynleighsmith and the posters a heads-up that if they see this artifact of a manually-positioned advertisement on older stories, that they can go in and remove the element, republish the story, and it will fix the issue.

**Comment by robynleighsmith** [comment]
@phillipadsmith I'm wondering when to send posters the "how to post for the new page design" update. Maybe tomorrow, once we've confirmed all the issues are sorted? I can send them a heads up now to say it's coming soon.

**Comment by phillipadsmith** [comment]
Yes, I would propose tomorrow afternoon.

**Comment by robynleighsmith** [comment]
OK, in that case I should send a general update to everyone about where the project is at, and that we still plan to start tomorrow afternoon with everything in place by Thursday morning.

Oy, I hope we're ready.
