### ISSUE TITLE
Gallery story issues

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#238]
This story seems to have a whack of problems:
http://preview.thetyee.ca/News/2015/02/23/Four-Sisters-Coop-Profile/

Wondering if the `gallery_output` story type is a work in progress at the moment, @MrBryan

**Comment by MrBryan** [comment]
Hmm well not really it should be working I can't remember which ones I looked at before.  That one didn't have the "series" story for it previewed so it looked extra bad -- i just previewed all of those for 2016 now so looks better.

But yes the float and clear stuff isn't working right. The nested elements for the gallery are the same as on the library story (in fact it is the sam set of images) far as I can tell but there are a lot of asides etc.

It works ok if I move the figure element in the inspector further down so it doesn't like being the first before paragraphs.  Maybe we need to move them up into the feature area if we want them first so will have to detect the presence of that element and put it up there instead of using the element template in the flow

**Comment by phillipadsmith** [comment]
> That one didn't have the "series" story for it previewed so it looked extra bad -- i just previewed all of those for 2016 now so looks better.

Ah, okay, makes sense.

> It works ok if I move the figure element in the inspector further down so it doesn't like being the first before paragraphs. Maybe we need to move them up into the feature area if we want them first so will have to detect the presence of that element and put it up there instead of using the element template in the flow

Not totally following here...

**Comment by MrBryan** [comment]
> Not totally following here...

Just saying if the element is in the regular flow where `<p>` elements are , it must not be the first one (must be after a p).

So I would have to move those things up to the top where the featured media section is. Which shouldn't be that hard actually because those types of stories always have that element I think

**Comment by MrBryan** [comment]
Or we can fix that issue

**Comment by phillipadsmith** [comment]
> Just saying if the element is in the regular flow where <p> elements are , it must not be the first one (must be after a p).

Still not following? This issue is about the gallery_output.mc specifically, and I'm thinking you're referring to something else?

**Comment by MrBryan** [comment]
No we're talking about the same thing. The gallery_output handles "gallery stories" that are just a bunch of related images.  When I use them to make a slideshow per the library usage, it does not display correctly in some cases, such as the one you referenced above.  It seems that the problem resolves when the gallery is after at least one p element rather than the first item in its container

**Comment by phillipadsmith** [comment]
> No we're talking about the same thing. The gallery_output handles "gallery stories" that are just a bunch of related images. When I use them to make a slideshow per the library usage, it does not display correctly in some cases, such as the one you referenced above. It seems that the problem resolves when the gallery is after at least one p element rather than the first item in its container

Ah, okay, I understand what you're saying now. Many thanks for clarifying.

Is there an potential solution?

**Comment by MrBryan** [comment]
d63d4c9 fixes the issue of first element as figure gallery. No other issues appear to be gallery specific unless you see any?

**Comment by phillipadsmith** [comment]
👍

**Comment by alexgreen** [comment]
Looks good now but there's an odd thing about this story:
It has a Tyee Series box but no Series badge. How come? Those two things should always accompany each other.

**Comment by alexgreen** [comment]
I opened a new ticket for the badge issue: #313
